status = [
    "CheckActiveClusters",
]
required_approvals = 0
use_codeowners = true
use_squash_merge = true
pr_status = ["CheckActiveClusters"]
timeout_sec = 300
delete_merged_branches = true
committer.name = "[bot] BorsNg"
